npm install -g bower
npm install -g coffee-script
npm install -g eslint
npm install -g grunt-cli
npm install -g gulp
npm install -g less
npm install -g lineman
npm install -g mocha
npm install -g yo
npm install -g node-inspector
npm install -g nodemon
npm install -g generator-aspnet
npm install -g generator-express
